### ISSUE TITLE
Detect direct links

### ISSUE THREAD

**Issue by Rexogamer** [incompetenator/discord-relink#6]
The bot currently responds to direct links; eg if I typed https://reddit.com/r/git. I feel the bot should not respond in these cases as it’s kinda spammy.

**Comment by chmltn** [comment]
Thank's for the feedback!

I agree with you; this is a bug. I'll find some way to detect direct Reddit links.

**Comment by chmltn** [comment]
I think I found a solution. I created a new branch with the fix.

**Comment by Rexogamer** [comment]
Took a look at the branch; mostly good, but I feel it would detect *all* URLs, not just Reddit ones.

**Comment by chmltn** [comment]
I responded in the other thread:
> Yes, which is what I intended.
> 
> There is an issue with detecting only Reddit links. Say links to something like https://www.twitter.com/twitter/. Since `r/` can be found at the end of the URL, the bot will respond. This may be a small issue, but still a possible occurrence. I don't want the bot responding seemingly randomly to users.
> 
> I can't think of any other solutions to this issue as of now. If you have a better solution, please feel free to tell me.

**Comment by chmltn** [comment]
I am going to merge the branch to master and close this issue. Thanks again for the feedback!
