### ISSUE TITLE
NSFW subreddits show as non existent (with the NSFW notice)

### ISSUE THREAD

**Issue by Rexogamer** [incompetenator/discord-relink#8]
Might be related to this code:
https://github.com/incompetenator/reddit-relink-bot/blob/6a5d521c1948d45e91dd186b22ffdff6a7721411/bot.py#L96-L98

**Comment by chmltn** [comment]
Ah, I must've missed that when I was writing. Nice catch!
This should fix it:
https://github.com/incompetenator/reddit-relink-bot/blob/a0286779a1765b62d87918ece8481e22606fc9a8/bot.py#L96-L97
I'll merge the branches and release a patch as soon as I can verify this works 100%.

**Comment by chmltn** [comment]
Alright, I've done some testing, and this patch seems to fix the issue. Reopen the issue (wait, can you do that? if not, just open a new issue) if you think the patch does not solve the issue.
